/* Generated by Yosys 0.33 (git sha1 2584903a060) */

module sign_extract(valid, cal_mode_comp, ab_sel, d15, d16, sign_valid, sign_pos, sign_neg, inc_i, dec_i);
  wire _00_;
  wire _01_;
  wire _02_;
  wire _03_;
  wire _04_;
  input ab_sel;
  wire ab_sel;
  input cal_mode_comp;
  wire cal_mode_comp;
  input d15;
  wire d15;
  input d16;
  wire d16;
  output dec_i;
  wire dec_i;
  output inc_i;
  wire inc_i;
  output sign_neg;
  wire sign_neg;
  output sign_pos;
  wire sign_pos;
  output sign_valid;
  wire sign_valid;
  input valid;
  wire valid;
  assign _02_ = ~d16;
  assign _03_ = ~d15;
  assign _04_ = d16 & _03_;
  assign _00_ = _02_ & d15;
  assign _01_ = d16 ^ d15;
  assign sign_valid = valid & _01_;
  assign dec_i = valid & _04_;
  assign inc_i = valid & _00_;
  assign sign_neg = dec_i;
  assign sign_pos = inc_i;
endmodule
